### PR TITLE
Convert to noarch: python

### PR DESCRIPTION
**Pull request by dbast**
Convert to noarch: python (the package is pure python without compiled code) to make it available on more platforms, like linux-ppc64le or osx-arm64.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dbast** [comment]
@conda-forge-admin, please rerender

**Comment by dbast** [comment]
@vinisalazar Ready for review/merge. thx

**Comment by dbast** [comment]
ping

**Review by vinisalazar — APPROVED** [review]
LGTM thank you @dbast

**Pull request merged**
